# theme       : jekyll-theme-slate
title       : "NDS-Shop-db"
description : "NDS-Shop-db - An online database of DS games in Universal-Updater"
repo        : "TheRinzler65/NDS-Shop-db"
color       : "#1d8056"
image       : "https://raw.githubusercontent.com/TheRinzler65/NDS-Shop-db/main/nds-shop-_logo.png"

sass:
  sass_dir: _sass

collections:
  3ds:
    output: false
  ds:
    output: true
