# theme       : jekyll-theme-slate
title       : "NDS-Shop"
description : "NDS-Shop - An online database of DS games in Universal-Updater"
repo        : "TheRinzler65/NDS-Shop"
color       : "#1d8056"
image       : "https://universal-team.net/images/icons/universal-team.png"

sass:
  sass_dir: _sass

collections:
  3ds:
    output: false
  ds:
    output: true
