name: Update sources

on:
  schedule:
    - cron: 0 0,6,12,18 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: rinzler65/nds-shop

    steps:
    - uses: actions/checkout@v1

    - name: Delete old pages and QRs
      run: rm -rf docs/_3ds/* docs/_ds/* docs/assets/images/qr/*.png

    - name: Run generate.py
      run: |
        export PATH=$PATH:/opt/devkitpro/tools/bin
        python3 source/generate.py

    - name: Pull origin
      run: git pull origin master --ff-only

    - name: Push changes
      run: |
        git config user.email "ndsshopunistore@gmail.com"
        git config user.name "NDS_Shop_Bot"

        echo "machine github.com" > "$HOME/.netrc"
        echo "  login NDS_Shop_Bot" >> "$HOME/.netrc"
        echo "  password ${{ secrets.MY_GITHUB_TOKEN }}" >> "$HOME/.netrc"

        echo "machine api.github.com" >> "$HOME/.netrc"
        echo "  login NDS_Shop_Bot" >> "$HOME/.netrc"
        echo "  password ${{ secrets.MY_GITHUB_TOKEN }}" >> "$HOME/.netrc"

        git checkout master
        git stage .
        if git commit -m "Update unistore"; then
          git push origin master
        fi