name: Update UniStore

# Run on push and 8 times per day
on:
  schedule:
    - cron: 0 0,3,6,9,12,15,18,21 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: rinzler65/nds-shop

    steps:
    - uses: actions/checkout@v1

    - name: Configure Git to trust the directory
      run: git config --global --add safe.directory /__w/NDS-Shop-db/NDS-Shop-db

    - name: Delete old pages and QRs
      run: rm -rf docs/_3ds/* docs/_ds/* docs/assets/images/qr/*.png

    - name: Run generate.py
      run: |
        export PATH=$PATH:/opt/devkitpro/tools/bin
        python3 source/generate.py source/apps docs

    - name: Pull origin
      run: git pull origin main --ff-only

    - name: Push changes
      run: |
        git config user.email "ndsshopunistore@gmail.com"
        git config user.name "NDS_Shop_Bot"

        echo "machine github.com" > "$HOME/.netrc"
        echo "  login NDS_Shop_Bot" >> "$HOME/.netrc"
        echo "  password ${{ secrets.MY_GITHUB_TOKEN }}" >> "$HOME/.netrc"

        echo "machine api.github.com" >> "$HOME/.netrc"
        echo "  login NDS_Shop_Bot" >> "$HOME/.netrc"
        echo "  password ${{ secrets.MY_GITHUB_TOKEN }}" >> "$HOME/.netrc"
        
        git checkout main
        git stage .
        if git commit -m "Update UniStore"; then
          git push origin main
        fi